on:
  pull_request:
    branches:
      - main
    paths:
      - "src/Saas.SignupAdministration/**"
      - ".github/**"

name: CI/CD - PR - Container Image Build and Webhook - Saas.SignupAdministration.Web

jobs: 
  build-image:
    name: Build and Publish Image
    uses: Azure/azure-saas/.github/workflows/template-container-image-build.yml@main
    with:
      image_to_push: asdk-signup
      tag_name: PR_$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

  # Add webhook jobs below here for each environment you want to automatically update
  webhook-dev:
    name: Image Build Webhook - Dev
    needs: build-image
    if: needs.build-image.result == 'success'
    uses: Azure/azure-saas/.github/workflows/template-container-image-webhook.yml@main
    secrets:
      WEBHOOK_URL: ${{ secrets.ASDK_SIGNUP_DEV_WEBHOOK_URL }}